name: Run unit tests

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: ['3.6', '3.9']
        
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
        
    - name: Install dependencies
      run: pip install -r requirements.txt
      
    - name: Run Unit Tests
      run: |
        python uniTest.py
        #TOTAL_TESTS=$(python uniTest.py -f | grep -c "Ran ")
        #PASSED_TESTS=$(python uniTest.py -f | grep -c "OK")
        #SUCCESS_RATE=$(echo "scale=2; $PASSED_TESTS/$TOTAL_TESTS*100" | bc)
        #if (( $(echo "$SUCCESS_RATE < 80.0" | bc -l) )); then
        #  echo "Less than 80% of tests passed. Reverting the push."
        #  git reset --hard HEAD^1
        #  exit 1
        #else
        #  echo "80% or more of tests passed."
        #fi


