name: Run unit tests

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: ['3.6']
        
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
        
    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run unit tests
      run: python uniTest.py
      
    - name: Install coverage
      run: pip install coverage

    - name: Check code coverage
      run: |
        coverage run uniTest.py
        COVERAGE=$(coverage report -m)
        COVERAGE_PERCENT=$(echo $COVERAGE | awk '{print $NF}' | sed 's/.$//' | sed 's/\./,/')
        if (( $(echo "$COVERAGE_PERCENT < 80.0" | bc -l) )); then
          echo "Code coverage is less than 80%. Reverting the push."
          git reset --hard HEAD^1
          exit 1
        else
          echo "Code coverage is greater than or equal to 80%."
        fi
